[general]
; 日志配置
log_level = INFO

[whisper]
; Whisper模型配置
model = erax-ai/EraX-WoW-Turbo-V1.1-CT2
device = cuda
download_root = ./data/whisper
timeout_seconds = 300

[ultralytics]
; YOLO模型配置
model_path = ./data/yolo11n.pt
; model_path = ./data/yoloe-11s-seg.pt

[openai]
; OpenAI API配置
api_key = AIzaSyBbYJxTtwXh7pcK-OmSvZ3qxiM7gIkcMy0
base_url = http://10.1.3.26:8888/v1beta/openai 